### ISSUE TITLE
Adding a relationship should not display more than one dialog

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2024sp-420-JavaA#278]
<img width="583" alt="Screenshot 2024-04-22 at 20 23 27" src="https://github.com/mucsci-students/2024sp-420-JavaA/assets/2007799/f1cc604b-2fc0-4ce6-86b6-b32738e29186">
<img width="470" alt="Screenshot 2024-04-22 at 20 23 33" src="https://github.com/mucsci-students/2024sp-420-JavaA/assets/2007799/12e6363e-c702-4026-89c6-5c51503721cd">
<img width="455" alt="Screenshot 2024-04-22 at 20 23 40" src="https://github.com/mucsci-students/2024sp-420-JavaA/assets/2007799/07e8a591-b455-4e74-bde5-af1d61c2a0ee">

**Comment by Natijc** [comment]
Made it into one dialog.
