### ISSUE TITLE
Adding a uniquely named field yields an error?

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2024sp-420-JavaA#285]
<img width="365" alt="Screenshot 2024-04-22 at 20 34 56" src="https://github.com/mucsci-students/2024sp-420-JavaA/assets/2007799/2bfd41f8-71b5-4936-ae63-6376bbd8fdc7">
<img width="526" alt="Screenshot 2024-04-22 at 20 35 01" src="https://github.com/mucsci-students/2024sp-420-JavaA/assets/2007799/f992e62f-0302-47ec-8eeb-551111f45908">

**Comment by Simatesh** [comment]
completed
