### ISSUE TITLE
I cannot create a method with no parameters

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2024sp-420-JavaA#287]
<img width="374" alt="Screenshot 2024-04-22 at 20 37 23" src="https://github.com/mucsci-students/2024sp-420-JavaA/assets/2007799/4f853e9f-c837-4dfa-ada9-0571cd7f972f">
<img width="669" alt="Screenshot 2024-04-22 at 20 38 01" src="https://github.com/mucsci-students/2024sp-420-JavaA/assets/2007799/8af4c388-b36f-45c9-9609-627cf75acaf6">

**Comment by Simatesh** [comment]
completed.
